require('chromedriver')
const {Builder, By, Key, until} = require('selenium-webdriver')

console.log('Start')

let driver = new Builder().forBrowser('chrome').build()
driver.get('http://localhost:8080/#/Login')

// login
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div/div/div[2]/input[1]')).sendKeys('superuser')
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div/div/div[2]/input[2]')).sendKeys('123qwe')
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div/div/div[3]/button')).click()
driver.sleep(1000)
// create Bot
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/button/i')).click()
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div/div[2]/div')).click()
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div/div[2]/div/div[1]/input[1]')).sendKeys('KoenigDaniel')
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div/div[2]/div/div[1]/input[2]')).sendKeys('Kniet vor eurer Majestät')
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div/div[2]/div/div[2]/button')).click()
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[1]/div[1]/div/img')).click()
driver.sleep(1000)

// edit the Bot
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div/div[14]/div/div[3]/div/button')).click()
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div[2]/div[2]/div[2]/div/button')).click()
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div[2]/div[2]/div[2]/div/div[2]/div/div[1]/input')).sendKeys('QUESTION')
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div[2]/div[2]/div[2]/div/div[2]/div/button')).click()
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div[2]/div[2]/div[2]/div/div[2]/div/div[2]/div/div[1]/input')).sendKeys('Boing!!!')
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[2]/div/div[2]/div[3]/div[2]/button')).click()
driver.sleep(1000)
driver.findElement(By.xpath('//*[@id="app"]/div/div[1]/div[1]/div/img')).click()
driver.sleep(1000)

console.log('Ending of the Test')
